# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 654)
        self.app_container = QtWidgets.QWidget(MainWindow)
        self.app_container.setObjectName("app_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.app_container)
        self.verticalLayout.setObjectName("verticalLayout")
        self.app = QtWidgets.QScrollArea(self.app_container)
        self.app.setWidgetResizable(True)
        self.app.setObjectName("app")
        self.app_scroll = QtWidgets.QWidget()
        self.app_scroll.setGeometry(QtCore.QRect(0, 0, 757, 616))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font")
        font.setPointSize(12)
        self.app_scroll.setFont(font)
        self.app_scroll.setToolTip("")
        self.app_scroll.setObjectName("app_scroll")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.app_scroll)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_app_title = QtWidgets.QLabel(self.app_scroll)
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font")
        font.setPointSize(24)
        font.setItalic(True)
        font.setStrikeOut(False)
        self.label_app_title.setFont(font)
        self.label_app_title.setObjectName("label_app_title")
        self.verticalLayout_2.addWidget(self.label_app_title, 0, QtCore.Qt.AlignHCenter)
        self.list_recently_moved = QtWidgets.QListView(self.app_scroll)
        self.list_recently_moved.setObjectName("list_recently_moved")
        self.verticalLayout_2.addWidget(self.list_recently_moved)
        self.btn_open_recently_moved = QtWidgets.QPushButton(self.app_scroll)
        self.btn_open_recently_moved.setObjectName("btn_open_recently_moved")
        self.verticalLayout_2.addWidget(self.btn_open_recently_moved)
        self.list_origin_folders = QtWidgets.QListView(self.app_scroll)
        self.list_origin_folders.setObjectName("list_origin_folders")
        self.verticalLayout_2.addWidget(self.list_origin_folders)
        self.btn_add_origin_folder = QtWidgets.QPushButton(self.app_scroll)
        self.btn_add_origin_folder.setObjectName("btn_add_origin_folder")
        self.verticalLayout_2.addWidget(self.btn_add_origin_folder)
        self.app.setWidget(self.app_scroll)
        self.verticalLayout.addWidget(self.app)
        MainWindow.setCentralWidget(self.app_container)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_app_title.setText(_translate("MainWindow", "BIBLIOTECARIO"))
        self.btn_open_recently_moved.setText(_translate("MainWindow", "ADD ORIGIN FOLDER"))
        self.btn_add_origin_folder.setText(_translate("MainWindow", "PushButton"))
